[build]
target = "avr-specs/avr-atmega128.json"

[target.'cfg(target_arch = "avr")']
runner = "java -jar ../avrora/avrora-beta-1.7.117.jar -monitors=c-print -single -platform=mica2"

[unstable]
build-std = ["core"]
